baseURL         = "http://matheper.com/"
languageCode    = "en"
title           = "Matheus Pereira"
theme           = "congo"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "AI Developer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Matheus Pereira blog"
  keywords = "matheper, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Matheus Pereira"
    subtitle = "Artificial Intelligence Developer"
    homeSubtitle = "Artificial Intelligence Developer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "matheper.com/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [languages.pt-br]
    title = "Matheus Pereira"
    subtitle = "Desenvolvedor - Inteligência Artificial"
    homeSubtitle = "Desenvolvedor - Inteligência Artificial"

    [languages.pt-br.params.logo]
      logoText = "matheper.com/"
      logoHomeLink = "/pt"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

